### ISSUE TITLE
Question about "https://gitlab.com/petrboros/retino/wikis/Merge-request/edit"

### ISSUE THREAD

**Issue by commentatorboy** [Krystofee/gitlab-unresolved-threads#5]
Inside your merge-request-checklist.js you have the following code:

https://github.com/Krystofee/gitlab-unresolved-threads/blob/master/merge-request-checklist.js#L20

I am not sure what the "https://gitlab.com/petrboros/retino/wikis/Merge-request/edit" part is used for.
Also that url leads to a 404. We should properly delete it or do something else with it?

**Comment by Krystofee** [comment]
Yeah you are right. Could you send me a PR to delete this file?

**Comment by commentatorboy** [comment]
Sure. https://github.com/Krystofee/gitlab-unresolved-threads/pull/6

Not sure why it says conflict though.

**Comment by commentatorboy** [comment]
Changed now it works.
